# Generated by Django 4.0.4 on 2022-05-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_content', models.CharField(default='', max_length=200)),
                ('choice1', models.CharField(default='', max_length=100)),
                ('choice2', models.CharField(default='', max_length=100)),
                ('choice3', models.CharField(default='', max_length=100)),
                ('choice4', models.CharField(default='', max_length=100)),
                ('answer', models.IntegerField(default=0)),
            ],
        ),
    ]
